### ISSUE TITLE
Some path variable not set correctly on Windows

### ISSUE THREAD

**Issue by wburgers** [Kotlin/kotlin-frontend-plugin#105]
Hi,
My coworker created a project which compiles to JS.
On his Mac, it works just fine.
On Windows I get an error for the same repository.
I have no clue what could be the problem, so any help would be appreciated.
```
10 09 2018 11:12:24.725:ERROR [karma]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:434:7)
    at Plugin.<anonymous> (C:\Development\projectname\jsfolder\build\node_modules\karma-webpack\lib\karma-webpack.js:262:68)
    at Plugin.readFile (C:\Development\projectname\jsfolder\build\node_modules\karma-webpack\lib\karma-webpack.js:281:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

the settings are as follows:
```
def outputDir = "${projectDir}/web/"

compileKotlin2Js {
    kotlinOptions.metaInfo = true
    kotlinOptions.sourceMap = true
    kotlinOptions.moduleKind = "commonjs"
    kotlinOptions.outputFile = "${outputDir}/${project.name}.js"
}

compileTestKotlin2Js {
    kotlinOptions.metaInfo = true
    kotlinOptions.sourceMap = true
    kotlinOptions.verbose = true
    kotlinOptions.sourceMapEmbedSources = "always"
    kotlinOptions.moduleKind = "commonjs"
    kotlinOptions.outputFile = "${outputDir}/${project.name}-test.js"
}

kotlinFrontend {
    downloadNodeJsVersion = 'latest'
    npm {
        dependency("uuid", "3.3.2")
        dependency("js-base64", "2.4.9")
        dependency("pkijs", "2.1.67")

        devDependency("karma")
        devDependency("karma-chrome-launcher")
        devDependency("kotlin")
        devDependency("qunit")
    }
    webpackBundle {
        mode = "development"
        sourceMapEnabled = true
    }
    karma {
        browsers = ["Chrome"]
        karma.plugins += ["karma-chrome-launcher"]
    }

    sourceMaps = true
}
```

**Comment by wburgers** [comment]
This issue resolved itself by removing the build folder and reinstalling everything.
I think the latest node/npm version was downloaded when reinstalling.
That may have been the fix.
