### ISSUE TITLE
Error: Cannot find module './build/WebPackHelper.js'

### ISSUE THREAD

**Issue by ideaBlender** [Kotlin/kotlin-frontend-plugin#144]
when running the custom-webpack-config example I get the following error

```
Error: Cannot find module './build/WebPackHelper.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/clegge/Projects/kotlin-frontend-plugin/examples/custom-webpack-config/webpack.config.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)

FAILURE: Build failed with an exception.
```

Have not modified the example at all...  Please let me know what i can do to help.

**Comment by ideaBlender** [comment]
if I ran the bundle command first, it creates the helper file... Is that intended?
