### ISSUE TITLE
Exception while relativizing source map

### ISSUE THREAD

**Issue by fhntv24** [Kotlin/kotlin-frontend-plugin#15]
OS: Windows 10
Java info:
>    java -version
>    java version "1.8.0_111"
>    Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
>    Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Kotlin version: 1.1.2-4 ( Also tried 1.1.2 and 1.1.4-dev-530 )
Plugin version: 0.0.19

Source map, that was generated using kotlin2js uses file://PATH_HERE ( for example file://F:/ ) URI's . While this is perfectly fine for windows, java doesn't like that and crashesh with exception. 
Stack trace:
```
Caused by: java.lang.IllegalArgumentException: URI has an authority component
        at org.jetbrains.kotlin.gradle.frontend.SourceMapsKt.relativizeSourceMap(SourceMaps.kt:53)
        at org.jetbrains.kotlin.gradle.frontend.SourceMapsKt.relativizeSourceMap$default(SourceMaps.kt:36)
        at org.jetbrains.kotlin.gradle.frontend.RelativizeSourceMapTask.relativize(SourceMaps.kt:30)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
```
Error is here: https://github.com/Kotlin/kotlin-frontend-plugin/blob/master/kotlin-frontend/src/main/kotlin/org/jetbrains/kotlin/gradle/frontend/SourceMaps.kt#L53

Some explanation:
First of all, any windows based path, that have disk name, will have :/. Because of that, check at line 52 will not work as intended with normal path.
And second reason, why it fails, is because java sees F: as authority ( aka domain ), and not as part of path.
This might be an error in kotlin2js, but I don't know. File("F:\\").toURI() gives file:/F/ , witch is perfectly fine for java, but not windows.

For now, I just added doLast to compileKotlin2Js that replaces file:\\\\ with file:\\\\\\

**Comment by dabeschte** [comment]
I'm having the same issue right now.
How did you convert the paths in doLast so they won't be handled like an uri?

**Comment by fhntv24** [comment]
```
doLast {
        File sourceMap = new File('./frontend/build/js/frontend.js.map')
        sourceMap.write(sourceMap.getText('UTF-8').replaceAll('file://', 'file:///'), 'UTF-8')
}
```
I could make it work with any configuration of sourceMap files, but really, I didn't need to.
Also, it's windows-only issue I think, so you could use ubuntu-bash on windows 10 or linux OS.
