### ISSUE TITLE
frontend-only example does not work

### ISSUE THREAD

**Issue by jonnyzzz** [Kotlin/kotlin-frontend-plugin#65]
I'm on macOS, no specific web stack configuration (still node/npm are installed).
`./gradlew test` in the `examples/frontend-only` folder

A problem was found with the configuration of task ':karma-config'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.
 - Directory '/Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/frontend-only/karma.config.d' specified for property '$1' does not exist.

> Task :karma-run-single FAILED
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'qunit'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at initQUnit (/Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/karma-qunit/lib/index.js:14:39)
    at Array.invoke (/Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/di/lib/injector.js:75:15)
    at Injector.get (/Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/di/lib/injector.js:48:43)
    at /Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/karma/lib/server.js:169:20
    at Array.forEach (<anonymous>)
    at Server._start (/Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/karma/lib/server.js:168:21)
    at Injector.invoke (/Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/karma/lib/server.js:129:18)
    at Object.exports.run (/Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/karma/lib/cli.js:286:26)
    at Object.<anonymous> (/Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/frontend-only/build/node_modules/karma/bin/karma:3:23)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)

FAILURE: Build failed with an exception.

**Comment by jonnyzzz** [comment]
added `dependency "qunit"` into `npm` block and it seems to work now

**Comment by cy6erGn0m** [comment]
This is fixed in 0.0.31
