### ISSUE TITLE
webpack (full-stack-example) does not run

### ISSUE THREAD

**Issue by jonnyzzz** [Kotlin/kotlin-frontend-plugin#67]
➜  full-stack-example git:(master) ✗ ./gradlew frontend:webpack-run\
>

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :frontend
Source map generation is not enabled for kotlin task compileTestKotlin2Js

> Task :frontend:webpack-run FAILED
webpack-dev-server exited with exit code 1, see /Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/full-stack-example/frontend/build/logs/webpack-dev-server.log
module.js:557
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jonnyzzz/Work/kotlin-frontend-plugin/examples/full-stack-example/frontend/build/webpack-dev-server-run.js:5:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

**Comment by jonnyzzz** [comment]
The `webpack-run` task does not seem to depend on `npm-install` task

**Comment by cy6erGn0m** [comment]
`webpack-run` doesn't but `run` does

**Comment by cy6erGn0m** [comment]
The other workaround is `./gradlew packages webpack-run`
